# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f45c05c3-876f-4ffd-b184-c6fc858aeb32";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime"];
    };

  boot.initrd.luks.devices = {
	"enc".device = "/dev/disk/by-uuid/6ff5706d-7d30-4db0-94b9-645e86df51c3";
	"optane".device = "/dev/disk/by-uuid/e9f50288-7c39-4b36-82d1-c86a142109ca";
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f45c05c3-876f-4ffd-b184-c6fc858aeb32";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f45c05c3-876f-4ffd-b184-c6fc858aeb32";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime"];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/f45c05c3-876f-4ffd-b184-c6fc858aeb32";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime"];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/f45c05c3-876f-4ffd-b184-c6fc858aeb32";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime"];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8695-1506";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/dev/mapper/optane";
  }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
